#!/usr/bin/env python

import argparse
from pathlib import Path

from script import maxpmap
from script.setting import parse_yaml
from script.utilities.logger import logger

VERSION = "0.1.0"


def protein_hotspot(setting):
    basedirpath = Path(setting["general"]["workdir"])
    JOB_NAME = setting["general"]["name"]

    logger.info("PMAP aggregation: mapPMAP")
    for map in setting["map"]["maps"]:
        inpaths = [str(p) for p in basedirpath.glob(f"system*/PMAP_{JOB_NAME}_{map['suffix']}.dx")]
        outpath = basedirpath / f"maxPMAP_{JOB_NAME}_{map['suffix']}.dx"
        maxpmap.gen_max_pmap(inpaths, str(outpath))
        logger.info(f"Output file: {outpath}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Calculate protein hotspot: aggregating PMAPs")
    parser.add_argument("setting_yaml", type=Path)
    parser.add_argument("-v,--verbose", dest="verbose", action="store_true")
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--version", action="version", version=VERSION)
    args = parser.parse_args()

    if args.debug:
        logger.setLevel("debug")
    elif args.verbose:
        logger.setLevel("info")
    # else: logger level is "warn"

    logger.info(f"read yaml: {args.setting_yaml}")
    setting = parse_yaml(args.setting_yaml)

    protein_hotspot(setting)
