#!/usr/bin/env python

import argparse
import glob
from pathlib import Path

from script import maxpmap
from script.utilities import util
from script.utilities.logger import logger

VERSION = "0.1.0"


def protein_hotspot(setting):
    basedirpath = setting["general"].workdir
    JOB_NAME = setting["general"].name

    logger.info("PMAP aggregation: mapPMAP")
    for map in setting["map"].maps:
        maxpmap.gen_max_pmap(
            glob.glob(f"{basedirpath}/system*/PMAP_{JOB_NAME}_{map['suffix']}.dx"),
            f"{basedirpath}/maxPMAP_{JOB_NAME}_{map['suffix']}.dx",
        )
        logger.info(f"Output file: {basedirpath}/maxPMAP_{JOB_NAME}_{map['suffix']}.dx")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Calculate protein hotspot: aggregating PMAPs")
    parser.add_argument("setting_yaml")
    parser.add_argument("-v,--verbose", dest="verbose", action="store_true")
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--version", action="version", version=VERSION)
    args = parser.parse_args()

    if args.debug:
        logger.setLevel("debug")
    elif args.verbose:
        logger.setLevel("info")
    # else: logger level is "warn"

    logger.info(f"read yaml: {args.setting_yaml}")
    setting = util.parse_yaml(Path(args.setting_yaml))

    protein_hotspot(setting)
