#!/usr/bin/env python

import argparse
import os 

import GPUtil
from joblib import Parallel, delayed
import yaml

from script.utilities import util
VERSION = "0.1.0"

from script.utilities.logger import logger

def protein_hotspot(setting):
    basedirpath = setting["general"]["workdir"]
    JOB_NAME = setting["general"]["name"]
    WORK_DIR = os.path.dirname(util.getabsolutepath(__file__))
    exe_python  = setting["general"]["executables"]["python"]

    logger.info("PELMAP aggregation: mapPELMAP")
    os.system(f"""
    {exe_python} {WORK_DIR}/script/maxpmap_main.py \
    {basedirpath}/system*/PELMAP_{JOB_NAME}_nVH.dx \
    {basedirpath}/maxPELMAP_{JOB_NAME}_nVH.dx
    """)
    logger.info(f"Output file: {basedirpath}/maxPELMAP_{JOB_NAME}_nVH.dx")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Calculate protein hotspot: aggregating PELMAPs")
    parser.add_argument("setting_yaml")
    parser.add_argument("-v,--verbose", dest="verbose", action="store_true")
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--version", action="version", version=VERSION)
    args = parser.parse_args()

    if args.debug:
        logger.setLevel("debug")
    elif args.verbose:
        logger.setLevel("info")
    # else: logger level is "warn"

    logger.info(f"read yaml: {args.setting_yaml}")
    setting = util.parse_yaml(args.setting_yaml)

    protein_hotspot(setting)