"""
RDKit Chem モジュールの型定義
"""

from typing import Any, Dict, List, Optional, Tuple, Union, overload

import numpy as np

# 循環インポートを避けるために、AllChemのインポートを削除
from rdkit.Chem import rdDepictor, rdFMCS

# rdGeometryモジュールをエクスポート
class rdGeometry:
    """rdGeometryモジュール"""
    class Point3D:
        """3次元座標点クラス"""
        def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
        @property
        def x(self) -> float: ...
        @property
        def y(self) -> float: ...
        @property
        def z(self) -> float: ...
        def __getitem__(self, idx: int) -> float: ...
        def __setitem__(self, idx: int, val: float) -> None: ...

class RDMol:
    """分子クラス"""
    def GetNumAtoms(self) -> int: ...
    def GetNumBonds(self) -> int: ...
    def GetAtomWithIdx(self, idx: int) -> 'Atom': ...
    def GetBonds(self) -> List['Bond']: ...
    def GetConformer(self, confId: int = 0) -> 'Conformer': ...
    def GetConformers(self) -> List['Conformer']: ...
    def GetSubstructMatch(self, query: 'RDMol') -> Tuple[int, ...]: ...
    def GetSubstructMatches(self, query: 'RDMol') -> List[Tuple[int, ...]]: ...
    def AddConformer(self, conf: 'Conformer', assignId: bool = True) -> int: ...

class Atom:
    """原子クラス"""
    def GetIdx(self) -> int: ...
    def GetSymbol(self) -> str: ...
    def GetBonds(self) -> List['Bond']: ...
    def GetNeighbors(self) -> List['Atom']: ...

class Bond:
    """結合クラス"""
    def GetIdx(self) -> int: ...
    def GetBeginAtomIdx(self) -> int: ...
    def GetEndAtomIdx(self) -> int: ...
    def GetBondType(self) -> Any: ...

class Conformer:
    """コンフォーマークラス"""
    def GetAtomPosition(self, idx: int) -> Any: ...
    def SetAtomPosition(self, idx: int, position: Any) -> None: ...

class EditableMol:
    """編集可能な分子クラス"""
    def __init__(self, mol: Optional[RDMol] = None) -> None: ...
    def AddAtom(self, atom: Atom) -> int: ...
    def AddBond(self, beginAtomIdx: int, endAtomIdx: int, order: Any = None) -> int: ...
    def GetMol(self) -> RDMol: ...

class RWMol(RDMol):
    """読み書き可能な分子クラス"""
    def __init__(self, mol: Optional[RDMol] = None) -> None: ...
    def AddAtom(self, atom: Atom) -> int: ...
    def AddBond(self, beginAtomIdx: int, endAtomIdx: int, order: Any = None) -> int: ...
    def RemoveAtom(self, idx: int) -> None: ...
    def RemoveBond(self, beginAtomIdx: int, endAtomIdx: int) -> None: ...
    def GetMol(self) -> RDMol: ...

class SDWriter:
    """SDFファイル書き込みクラス"""
    def __init__(self, fileName: str) -> None: ...
    def write(self, mol: RDMol) -> None: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...

class SDMolSupplier:
    """SDFファイル読み込みクラス"""
    def __init__(self, fileName: str, sanitize: bool = True, removeHs: bool = True, strictParsing: bool = True) -> None: ...
    def __getitem__(self, idx: int) -> Optional[RDMol]: ...
    def __len__(self) -> int: ...
    def reset(self) -> None: ...

def Mol(mol: Union[RDMol, str]) -> RDMol: ...
def MolFromSmarts(smarts: str) -> RDMol: ...
def MolFromSmiles(smiles: str, sanitize: bool = True) -> RDMol: ...
def MolFromMolFile(molFile: str, sanitize: bool = True, removeHs: bool = True) -> RDMol: ...
def MolToSmiles(mol: RDMol) -> str: ...
def MolToMolFile(mol: RDMol, fileName: str, includeStereo: bool = True, kekulize: bool = True) -> None: ...
def AddHs(mol: RDMol, explicitOnly: bool = False, addCoords: bool = False) -> RDMol: ...
def RemoveHs(mol: RDMol, implicitOnly: bool = False) -> RDMol: ...
def MolToMolBlock(mol: RDMol) -> str: ...
def MolFromMolBlock(molBlock: str, sanitize: bool = True, removeHs: bool = True) -> RDMol: ...
def MolFromMol2File(mol2File: str, sanitize: bool = True, removeHs: bool = True) -> RDMol: ...
def MolFromPDBFile(pdbFile: str, sanitize: bool = True, removeHs: bool = True, proximityBonding: bool = True) -> RDMol: ...