"""
RDKit AllChem モジュールの型定義
"""

from typing import Any, Dict, List, Optional, Tuple, Union, overload

import numpy as np

# RDMolを直接定義
class RDMol:
    """分子クラス"""
    def GetNumAtoms(self) -> int: ...
    def GetNumBonds(self) -> int: ...
    def GetAtomWithIdx(self, idx: int) -> Any: ...
    def GetBonds(self) -> List[Any]: ...
    def GetConformer(self, confId: int = 0) -> Any: ...
    def GetConformers(self) -> List[Any]: ...
    def GetSubstructMatch(self, query: 'RDMol') -> Tuple[int, ...]: ...
    def GetSubstructMatches(self, query: 'RDMol') -> List[Tuple[int, ...]]: ...
    def AddConformer(self, conf: Any, assignId: bool = True) -> int: ...

def GetMorganFingerprintAsBitVect(mol: RDMol, radius: int, nBits: int = 2048, invariants: Optional[List[int]] = None, fromAtoms: Optional[List[int]] = None, useChirality: bool = False, useBondTypes: bool = True, useFeatures: bool = False) -> Any: ...

def GetMorganFingerprint(mol: RDMol, radius: int, invariants: Optional[List[int]] = None, fromAtoms: Optional[List[int]] = None, useChirality: bool = False, useBondTypes: bool = True, useFeatures: bool = False) -> Any: ...

def EmbedMolecule(mol: RDMol, maxAttempts: int = 0, randomSeed: int = -1, clearConfs: bool = True, useRandomCoords: bool = False, boxSizeMult: float = 2.0, randNegEig: bool = True, numZeroFail: int = 1, coordMap: Optional[Dict[int, Tuple[float, float, float]]] = None, forceTol: float = 0.001, ignoreSmoothingFailures: bool = False, enforceChirality: bool = True, numThreads: int = 1, useExpTorsionAnglePrefs: bool = True, useBasicKnowledge: bool = True, printExpTorsionAngles: bool = False, useSmallRingTorsions: bool = False, useMacrocycleTorsions: bool = False, ETversion: int = 1, optimizeConfs: bool = False, pruneRmsThresh: float = -1.0) -> int: ...

def UFFOptimizeMolecule(mol: RDMol, maxIters: int = 200, vdwThresh: float = 10.0, confId: int = -1, ignoreInterfragInteractions: bool = True) -> int: ...

def MMFFOptimizeMolecule(mol: RDMol, maxIters: int = 200, confId: int = -1, mmffVariant: str = "MMFF94", nonBondedThresh: float = 100.0, ignoreInterfragInteractions: bool = True) -> int: ...

def Compute2DCoords(mol: RDMol, clearConfs: bool = True, canonOrient: bool = True, coordMap: Optional[Dict[int, Tuple[float, float]]] = None, nFlipsPerSample: int = 0, nSamples: int = 0, sampleSeed: int = 0, permuteDeg4Nodes: bool = False, bondLength: float = -1.0, forceRDKit: bool = False) -> None: ...

def GenerateDepictionMatching2DStructure(mol: RDMol, reference: RDMol, confId: int = -1, referencePattern: Optional[RDMol] = None, acceptFailure: bool = False, forceRDKit: bool = False, allowRGroups: bool = False) -> int: ...

def GetBestRMS(probe: RDMol, ref: RDMol, refConfId: int = -1, probeConfId: int = -1, maps: Optional[List[List[Tuple[int, int]]]] = None) -> float: ...

def GetConformerRMS(mol: RDMol, confId1: int, confId2: int, atomIds: Optional[List[int]] = None, prealigned: bool = False) -> float: ...

def GetConformerRMSMatrix(mol: RDMol, atomIds: Optional[List[int]] = None, prealigned: bool = False) -> np.ndarray: ...

def AlignMol(mol: RDMol, refMol: RDMol, prbCid: int = -1, refCid: int = -1, atomMap: Optional[List[Tuple[int, int]]] = None, maxIters: int = 50, weights: Optional[List[float]] = None) -> float: ...

def AlignMolConformers(mol: RDMol, atomIds: Optional[List[int]] = None, confIds: Optional[List[int]] = None, weights: Optional[List[float]] = None, maxIters: int = 50) -> List[float]: ...

def EnumerateStereoisomers(mol: RDMol, options: Optional[Any] = None, verbose: bool = False) -> List[RDMol]: ...

def AssignBondOrdersFromTemplate(refmol: RDMol, mol: RDMol) -> RDMol: ...