"""
RDKit DataStructs モジュールの型定義
"""

from typing import Any, List, Optional, Tuple, Union

def TanimotoSimilarity(fp1: Any, fp2: Any) -> float: ...
def DiceSimilarity(fp1: Any, fp2: Any) -> float: ...
def CosineSimilarity(fp1: Any, fp2: Any) -> float: ...
def SokalSimilarity(fp1: Any, fp2: Any) -> float: ...
def RusselSimilarity(fp1: Any, fp2: Any) -> float: ...
def KulczynskiSimilarity(fp1: Any, fp2: Any) -> float: ...
def McConnaugheySimilarity(fp1: Any, fp2: Any) -> float: ...
def TverskySimilarity(fp1: Any, fp2: Any, a: float, b: float) -> float: ...
def BulkTanimotoSimilarity(fp: Any, fpList: List[Any]) -> List[float]: ...
def BulkDiceSimilarity(fp: Any, fpList: List[Any]) -> List[float]: ...
def BulkCosineSimilarity(fp: Any, fpList: List[Any]) -> List[float]: ...
def BulkSokalSimilarity(fp: Any, fpList: List[Any]) -> List[float]: ...
def BulkRusselSimilarity(fp: Any, fpList: List[Any]) -> List[float]: ...
def BulkKulczynskiSimilarity(fp: Any, fpList: List[Any]) -> List[float]: ...
def BulkMcConnaugheySimilarity(fp: Any, fpList: List[Any]) -> List[float]: ...
def BulkTverskySimilarity(fp: Any, fpList: List[Any], a: float, b: float) -> List[float]: ...