"""
RDKit rdDepictor モジュールの型定義
"""

from typing import Any, Dict, List, Optional, Tuple, Union

# RDMolを直接定義
class RDMol:
    """分子クラス"""
    def GetNumAtoms(self) -> int: ...
    def GetNumBonds(self) -> int: ...
    def GetAtomWithIdx(self, idx: int) -> Any: ...
    def GetBonds(self) -> List[Any]: ...
    def GetConformer(self, confId: int = 0) -> Any: ...
    def GetConformers(self) -> List[Any]: ...
    def GetSubstructMatch(self, query: 'RDMol') -> Tuple[int, ...]: ...
    def GetSubstructMatches(self, query: 'RDMol') -> List[Tuple[int, ...]]: ...
    def AddConformer(self, conf: Any, assignId: bool = True) -> int: ...

def Compute2DCoords(mol: RDMol, clearConfs: bool = True, canonOrient: bool = True, coordMap: Optional[Dict[int, Tuple[float, float]]] = None, nFlipsPerSample: int = 0, nSamples: int = 0, sampleSeed: int = 0, permuteDeg4Nodes: bool = False, bondLength: float = -1.0, forceRDKit: bool = False) -> None: ...

def GenerateDepictionMatching2DStructure(mol: RDMol, reference: RDMol, confId: int = -1, referencePattern: Optional[RDMol] = None, acceptFailure: bool = False, forceRDKit: bool = False, allowRGroups: bool = False) -> int: ...