"""
RDKit rdFMCS モジュールの型定義
"""

from typing import Any, Dict, List, Optional, Tuple, Union

# RDMolを直接定義
class RDMol:
    """分子クラス"""
    def GetNumAtoms(self) -> int: ...
    def GetNumBonds(self) -> int: ...
    def GetAtomWithIdx(self, idx: int) -> Any: ...
    def GetBonds(self) -> List[Any]: ...
    def GetConformer(self, confId: int = 0) -> Any: ...
    def GetConformers(self) -> List[Any]: ...
    def GetSubstructMatch(self, query: 'RDMol') -> Tuple[int, ...]: ...
    def GetSubstructMatches(self, query: 'RDMol') -> List[Tuple[int, ...]]: ...
    def AddConformer(self, conf: Any, assignId: bool = True) -> int: ...

class MCSResult:
    """MCS計算結果クラス"""
    @property
    def numAtoms(self) -> int: ...
    @property
    def numBonds(self) -> int: ...
    @property
    def smartsString(self) -> str: ...
    @property
    def canceled(self) -> bool: ...

def FindMCS(mols: List[RDMol], minNumAtoms: int = 2, maximizeBonds: bool = True, threshold: float = 1.0, timeout: int = 3600, verbose: bool = False, matchValences: bool = False, ringMatchesRingOnly: bool = False, completeRingsOnly: bool = False, matchChiralTag: bool = False, atomCompare: Any = None, bondCompare: Any = None, seedSmarts: str = "", maximizeQueryAtoms: bool = True) -> MCSResult: ...