"""
RDKit rdGeometry モジュールの型定義
"""

from typing import Any, List, Optional, Tuple, Union

class Point3D:
    """3次元座標点クラス"""
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def __getitem__(self, idx: int) -> float: ...
    def __setitem__(self, idx: int, val: float) -> None: ...